### ISSUE TITLE
Add questions 

### ISSUE THREAD

**Issue by BekzodKeldiyarov** [cybersecurity-polito/wireless-exam#13]
Which of the following security services does WEP support? 
_**1. Data integrity
2. Message confidentiality 
3. Access control**_ 
4. Authentication 
5. None of the other options

Which of the following best defines an authentication service in the context of wireless networks? 

**_1. A service that verifies the identity of users or devices before granting access to network resources._**  
2. A service that encrypts data to ensure privacy during transmission. 
3. A service that manages user permissions and access levels within the network. 
4. None of the other options. 
5. A service that restricts access to network resources based on user identity and predefined policies.

**Comment by no-mood** [comment]
Added in the latest build. Thank you!
